Repository openshift/aws-ebs-csi-driver-operator, pull requests merged in 2020-04, with the labels that each got.

#9 Prepare for e2e test
  assets/controller_deployment.yaml
  assets/node_daemonset.yaml
  hack/start-manifests/99_deployment.yaml
  hack/start.sh
  manifests/00_crd.yaml
  manifests/02_namespace.yaml
  manifests/03_cr.yaml
  manifests/04_sa.yaml
  manifests/05_rbac.yaml
  manifests/README.md
  pkg/generated/bindata.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/starter.go
  pkg/operator/sync.go
  test/e2e/manifest.yaml
  test/e2e/storageclass.yaml
Labels: approved, lgtm

#15 Add test-e2e Makefile target
  .gitignore
  Makefile
  manifests/03_cr.yaml
Labels: approved, lgtm

#16 Rework e2e tests from Makefile to a script
  Makefile
  hack/e2e.sh
  hack/start.sh
Labels: approved, lgtm

#14 Bump openshift/library-go
  README.md
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
  vendor/modules.txt
Labels: approved, lgtm

#23 TODO list has been migrated to GH issues
  README.md
Labels: approved, lgtm

#24 Use /bin/oc when available in e2e tests
  hack/start.sh
Labels: approved, lgtm

#19 Add CredentialsRequest creation
  assets/credentials.yaml
  manifests/01_namespace.yaml
  manifests/02_cr.yaml
  manifests/03_sa.yaml
  manifests/04_rbac.yaml
  pkg/generated/bindata.go
  pkg/operator/credential_request.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/starter.go
  pkg/operator/sync.go
  pkg/operator/unstructured_test.go
Labels: approved, lgtm

#17 Update group of CRD
  manifests/0.1/aws-ebs-csi-operator.v0.1.clusterserviceversion.yaml
  manifests/00_crd.yaml
  manifests/02_cr.yaml
  pkg/apis/operator/register.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/driver.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/ebscsidriver.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/fake/fake_driver.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/fake/fake_ebscsidriver.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/fake/fake_operator_client.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/operator_client.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/operator/v1alpha1/driver.go
  pkg/generated/informers/externalversions/operator/v1alpha1/interface.go
  pkg/generated/listers/operator/v1alpha1/driver.go
  pkg/generated/listers/operator/v1alpha1/ebscsidriver.go
  pkg/generated/listers/operator/v1alpha1/expansion_generated.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/operatorclient.go
  pkg/operator/starter.go
  pkg/operator/sync.go
Labels: approved, lgtm

#27 Add image with e2e test scripts & manifests
  Dockerfile.test
Labels: approved, lgtm

#13 Add CSV for OLM
  assets/rbac/attacher_role.yaml
  hack/base-manifests/00_crd.yaml
  hack/base-manifests/01_namespace.yaml
  hack/base-manifests/02_cr.yaml
  hack/base-manifests/03_sa.yaml
  hack/base-manifests/04_rbac.yaml
  hack/start.sh
  manifests/0.1/aws-ebs-csi-operator.v0.1.clusterserviceversion.yaml
  manifests/4.5/aws-csi-driver.crd.yaml
  manifests/4.5/aws-ebs-csi-driver-operator.v4.5.0.clusterserviceversion.yaml
  manifests/README.md
  manifests/aws-ebs-csi-operator.package.yaml
  pkg/generated/bindata.go
  pkg/operator/operator.go
Labels: approved, lgtm

#28 Parse CSV to install the operator for e2e tests
  hack/base-manifests/00_crd.yaml
  hack/base-manifests/01_namespace.yaml
  hack/base-manifests/02_cr.yaml
  hack/base-manifests/03_sa.yaml
  hack/base-manifests/04_rbac.yaml
  hack/e2e.sh
  hack/start-manifests/99_deployment.yaml
  hack/start.sh
  hack/templates/00_crd.yaml
  hack/templates/01_namespace.json
  hack/templates/02_sa.json
  hack/templates/03_role.json
  hack/templates/04_rolebinding.json
  hack/templates/05_clusterrole.json
  hack/templates/06_clusterrolebinding.json
  hack/templates/07_deployment.json
  hack/templates/08_cr.json
  hack/yaml2json.py
Labels: approved, lgtm

#29 Validate CR name
  manifests/4.5/aws-csi-driver.crd.yaml
Labels: approved, lgtm

#30 Finish e2e test preparation
  Dockerfile.test
  hack/start.sh
Labels: approved, lgtm

#25 Make credentials secret required
  assets/controller_deployment.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm

#31 Add BZ component to OWNERS
  OWNERS
Labels: approved, lgtm

#33 Remove hostmount-anyuid SCC from the operator
  manifests/4.5/aws-ebs-csi-driver-operator.v4.5.0.clusterserviceversion.yaml
Labels: approved, lgtm

#34 Wait for pods before starting e2e tests
  hack/e2e.sh
Labels: approved, lgtm

#35 Add index image
  Dockerfile
  Dockerfile.rhel7
  README.md
  bundle/bundle.Dockerfile
  bundle/manifests/aws-csi-driver.crd.yaml
  bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  hack/start.sh
  hack/templates/00_crd.yaml
  manifests/aws-ebs-csi-operator.package.yaml
Labels: approved, lgtm

#38 Use quay.io for the operator and driver images
  assets/controller_deployment.yaml
  assets/node_daemonset.yaml
  bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
  hack/start.sh
  pkg/generated/bindata.go
  pkg/operator/operator_test.go
Labels: approved, lgtm

#39 Fix Dockerfile typo
  Dockerfile.rhel7
Labels: approved, lgtm

#32 Update the operand when image changes
  pkg/operator/credential_request.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/sync.go
Labels: approved, lgtm

#40 Document how to install OPM tool
  README.md
Labels: approved, lgtm

#43 Bug 1826285: Don't delete driver if CR doesn't exist
  pkg/operator/operator.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm

#46 Bug 1827099: Add suggested namespace for driver install
  bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#50 Bug 1827638: Rename CRD to AWSEBSDriver
  README.md
  bundle/manifests/aws-csi-driver.crd.yaml
  bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
  hack/e2e.sh
  hack/templates/08_cr.json
  pkg/apis/operator/register.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/awsebsdriver.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/driver.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/fake/fake_awsebsdriver.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/fake/fake_driver.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/fake/fake_operator_client.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/operator/v1alpha1/operator_client.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/operator/v1alpha1/awsebsdriver.go
  pkg/generated/informers/externalversions/operator/v1alpha1/interface.go
  pkg/generated/listers/operator/v1alpha1/awsebsdriver.go
  pkg/generated/listers/operator/v1alpha1/driver.go
  pkg/generated/listers/operator/v1alpha1/expansion_generated.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/operatorclient.go
  pkg/operator/starter.go
  pkg/operator/sync.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#49 Bug 1827130: Rebase to new library-go
  go.mod
  go.sum
  pkg/operator/operator_test.go
  pkg/operator/sync.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apps.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/core.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/modules.txt
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#51 Bug 1828963: Fix the operator CSV and CRD
  bundle/manifests/aws-csi-driver.crd.yaml
  bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
