Repository openshift/aws-ebs-csi-driver-operator, pull requests merged in 2020-05, with the labels that each got.

#52 Bug 1835604: Add defaulting to driver.Spec fields
  bundle/manifests/aws-csi-driver.crd.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#53 Bug 1835716: Allow the operator to be installed only once
  bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#55 Bug 1836834: Remove VERSION env. variables
  bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
  pkg/operator/credential_request.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/starter.go
  pkg/operator/sync.go
  vendor/github.com/openshift/library-go/pkg/config/clusteroperator/v1helpers/status.go
  vendor/github.com/openshift/library-go/pkg/operator/status/condition.go
  vendor/github.com/openshift/library-go/pkg/operator/status/inertia.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/version.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#54 Bug 1835726: Report error conditions on CredentialsRequest on the driver CR
  pkg/operator/credential_request.go
  pkg/operator/credential_request_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#57 Bug 1836834: Rename env. variables
  bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
  pkg/operator/operator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#56 Bug 1835778: Detect CSI driver installed by cluster admin
  assets/csidriver.yaml
  pkg/generated/bindata.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/starter.go
  pkg/operator/sync.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#58 Bug 1835726: Actually use error message from the credentials operator
  pkg/operator/operator.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#60 Bug 1839720: Revert "Add defaulting to driver.Spec fields"
  bundle/manifests/aws-csi-driver.crd.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#59 Bug 1834662: Set proper conditions when running in wrong platform
  bundle/manifests/aws-ebs-csi-driver-operator.clusterserviceversion.yaml
  pkg/common/builder.go
  pkg/common/controller_context.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/operator/starter.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_operatorhub.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_scheduler.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
