Repository openshift/aws-ebs-csi-driver-operator, pull requests merged in 2021-04, with the labels that each got.

#118 Fix kube-rbac-proxy image reference
  assets/controller.yaml
  go.mod
  go.sum
  pkg/generated/bindata.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivernodeservicecontroller/csi_driver_node_service_controller.go
  vendor/modules.txt
Labels: approved, lgtm

#119 Bug 1924470: Bump Kubernetes to 1.21
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/operator/v1helpers/args.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#121 Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/metrics/metrics.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#120 Bug 1947774: fix imagePullPolicy to ifNotPresent
  assets/controller.yaml
  assets/node.yaml
  pkg/generated/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
