Repository openshift/aws-ebs-csi-driver-operator, pull requests merged in 2021-02, with the labels that each got.

#111 Bug 1905119: dynamically update controller asset for custom CA bundle
  assets/controller.yaml
  pkg/generated/bindata.go
  pkg/operator/starter.go
  pkg/operator/starter_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#113 Cleanup: Remove serviceName from controller manifest
  assets/controller.yaml
  pkg/generated/bindata.go
Labels: approved, lgtm

#105 Bug 1912720: Remove stale ResourceSyncControllerDegraded condition
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
