Repository openshift/aws-ebs-csi-driver-operator, pull requests merged in 2022-12, with the labels that each got.

#167 OCPBUGS-3990: Add HyperShift specific priorityClass
  pkg/operator/starter.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-critical

#168 OCPBUGS-4347: set TLS cipher suites in Kube RBAC sidecars
  assets/controller.yaml
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/config/serving/server.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-moderate

#169 OCPBUGS-4491: hypershift: use correct kubeconfig secret
  pkg/operator/starter.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug
