Repository openshift/aws-ebs-csi-driver-operator, pull requests merged in 2023-01, with the labels that each got.

#174 STOR-1078: Add hostPaths necessary for SELinux mounts
  assets/node.yaml
Labels: lgtm, approved, docs-approved, qe-approved, px-approved

#175 Bug 2106736: Add multiplePVsSameID capability
  test/e2e/manifest.yaml
Labels: bugzilla/valid-bug, lgtm, approved, bugzilla/severity-medium

#178 [#177] fix 404 in readme
  README.md
Labels: lgtm, approved, ok-to-test, docs-approved, qe-approved, px-approved
