Repository openshift/aws-ebs-csi-driver-operator, pull requests merged in 2023-07, with the labels that each got.

#244 STOR-1065: Rework sidecar bindings to bind common ClusterRoles
  assets/rbac/attacher_role.yaml
  assets/rbac/lease_leader_election_role.yaml
  assets/rbac/lease_leader_election_rolebinding.yaml
  assets/rbac/main_attacher_binding.yaml
  assets/rbac/main_provisioner_binding.yaml
  assets/rbac/main_resizer_binding.yaml
  assets/rbac/main_snapshotter_binding.yaml
  assets/rbac/provisioner_role.yaml
  assets/rbac/resizer_role.yaml
  assets/rbac/snapshotter_role.yaml
  assets/rbac/storageclass_reader_resizer_binding.yaml
  assets/rbac/volumesnapshot_reader_provisioner_binding.yaml
  pkg/operator/starter.go
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#248 OCPBUGS-15823: Change CSI RPC call timeouts
  assets/controller.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#220 OCPBUGS-13036: 4.13: Bump (golang.org/x/net): to address CVE-2022-41723
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.c
  vendor/golang.org/x/sys/cpu/endian_big.go
  vendor/golang.org/x/sys/cpu/endian_little.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#251 OCPBUGS-16783: Chore: Update OWNERS
  OWNERS
Labels: lgtm, approved, jira/severity-low, jira/valid-bug, jira/valid-reference
