Repository openshift/aws-ebs-csi-driver-operator, pull requests merged in 2023-03, with the labels that each got.

#185 STOR-875: Implement custom keys in AWS EBS CSI driver operator
  go.mod
  go.sum
  pkg/operator/starter.go
  pkg/operator/storageclasshook.go
  pkg/operator/storageclasshook_test.go
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml-patch
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
  vendor/github.com/openshift/api/config/v1/stable.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/stable.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.apiserver.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/techpreview.infrastructure.testsuite.yaml
  vendor/github.com/openshift/api/config/v1/types_apiserver.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1/types_nutanixprovider.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/machine/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/machine/v1beta1/types_gcpprovider.go
  vendor/github.com/openshift/api/machine/v1beta1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: lgtm, approved, docs-approved, qe-approved, px-approved, jira/valid-reference

#194 OCPBUGS-8752: feat: add workload annotation to deployment and daemonset
  assets/controller.yaml
  assets/node.yaml
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#198 OCPBUGS-8752: fix: typo
  assets/controller.yaml
  assets/node.yaml
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#199 [release-4.13] OCPBUGS-10405: feat: add workload annotation to deployment and daemonset
  assets/controller.yaml
  assets/node.yaml
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#205 OCPBUGS-8691: Hypershift: set control plane operand properties
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/config/leaderelection/leaderelection.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/cmd.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/csi_driver_controller_service_controller.go
  vendor/modules.txt
Labels: bugzilla/valid-bug, lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference
